# ===============================
# DATABASE CONNECTION
# ===============================

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mm-um-backend-db:5432/mm
    username: muser
    password: muser

  # ===============================
  # JPA / HIBERNATE
  # ===============================

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: com.myprod.mymessenger.user.manager.hibernate.dialect.CustomPostgreSqlDialect

        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    url: jdbc:postgresql://mm-um-backend-db:5432/mm?encoding=utf8&useUnicode=true&characterEncoding=UTF-8
    locations: [ "filesystem:src/main/resources/db/migration" ]
    baselineVersion: 1
    user: "muser"
    password: "muser"

  # ===============================
  # SECURITY
  # ===============================
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  tomcat:
    max-threads: 5
