version: "3.8"

services:

  mm-um-backend-app-test:
    build:
      context: ./env/backend
      dockerfile: DockerfileTest
    container_name: mm-um-backend-app-test
    command: gradle build --continuous
    tty: true
    volumes:
      - ./backend/src:/app/src
      - ./backend/build.gradle:/app/build.gradle
      - ./backend/settings.gradle:/app/settings.gradle
      - mm-um-backend-app-test-build:/app/build:Z
    networks:
      - mm-um-backend-test-network

  mm-um-backend-db-test:
    image: postgres:13.2-alpine
    container_name: mm-um-backend-db-test
    environment:
      POSTGRES_USER: muser
      POSTGRES_PASSWORD: muser
      POSTGRES_DB: mm
    volumes:
      - mm-um-backend-db-config-data-test:/var/lib/postgresql/data
      - ./log/backend-test/postgres:/log/postgresql
      - ./env/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - mm-um-backend-test-network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

networks:
  mm-um-backend-test-network:
    name: mm-um-backend-test-network

volumes:
  mm-um-backend-db-config-data-test:
  mm-um-backend-app-test-build:
