version: "3.7"

services:

  mymessenger-user-manager-frontend:
    build: env/frontend
    container_name: mymessenger-user-manager-frontend
    tty: true
    user: 1000:1000
    volumes:
      - ./frontend:/app
    networks:
      - mymessenger-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.user-manager-frontend.rule=Host(`user-manager.mymessenger.local`)

networks:
  mymessenger-network:
    name: mymessenger-network
    external: true
