version: "3.8"

services:

  mm-um-frontend:
    build: env/frontend
    container_name: mm-um-frontend
    tty: true
    user: 1000:1000
    volumes:
      - ./frontend:/app
    networks:
      - mm-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.um-frontend.rule=Host(`um.mm.local`)

networks:
  mm-network:
    name: mm-network
    external: true
