# ===============================
# DATABASE CONNECTION
# ===============================

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mymessenger-user-manager-backend-db:5432/mymessenger
    username: mymess
    password: pass

  # ===============================
  # JPA / HIBERNATE
  # ===============================

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: com.myprod.mymessenger.user.manager.hibernate.dialect.CustomPostgreSqlDialect

        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false

  # ===============================
  # SECURITY
  # ===============================
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  tomcat:
    max-threads: 5
