version: "3.8"

services:

  mm-proxy:
    image: traefik:v2.4.2
    container_name: mm-proxy
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mm-network

networks:
  mm-network:
    name: mm-network
